FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    ca-certificates \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY hello.py /app/hello.py

CMD ["python3", "/app/hello.py"]
